### ISSUE TITLE
2 příklady z první lekce

### ISSUE THREAD

**Issue by VendyNyu** [VendyNyu/python-012021#1]
Ahoj, 
prosím o kontrolu prvního a druhého příkladu z lekce 1. 

@pesikj Issue mi nelze přiřadit na Aleše (kkukpostcz). V sekci Manage access mám stále stav Pending Invite, tak mu to případně předej. 

Díky moc :) 
Vendy

**Comment by pesikj** [comment]
Ahoj Vendy, za mě jsou první tři příklady super :-) Aleš nemá v práci možnost se dostat na Git, ale určitě se tu brzy objeví :-)
Jirka

**Comment by VendyNyu** [comment]
Super, díky moc :)
