### ISSUE TITLE
Zadání u lekce 2 příklad 10

### ISSUE THREAD

**Issue by VendyNyu** [VendyNyu/python-012021#4]
Ahoj, prosím tě není chyba v zadání u tohoto příkladu? 
Obchodníci v naší softwarové firmě používají jednoduchý systém, aby odhadli šanci na úspěch potenciální zakázky. Každé zakázce přiřadí body od 0 do 10 a platí:

Pokud má zakázka méně než 5 bodů, šance na záskání je malá.
Pokud má zakázka 6 až 8 bodů, šance na získání je střední.
Pokud má zakázka více bodů, šance na získání je vysoká.

Protože, takhle by to bylo: 
0-4 - šance malá 
6-8 - šance střední
8-10 - šance vysoká

**Comment by pesikj** [comment]
Ahoj, jasně, máš pravdu, pokud má 5 bodů, tak můžeš dát, že je šance taky malá :-)
